# Generated by Django 4.1.7 on 2023-02-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_initial"),
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="feed",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="feeds.feed"
            ),
            preserve_default=False,
        ),
    ]
